// Code generated by protoc-gen-go-grpc-local. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: user/v1/user.ext.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

type userExtClientLocal struct {
	impl UserExtServer
}

func NewUserExtClientLocal(impl UserExtServer) UserExtClient {
	return &userExtClientLocal{impl}
}

func (c *userExtClientLocal) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error) {
	return c.impl.GetUserInfo(ctx, in)
}
