// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8-devel
// 	protoc        v3.21.12
// source: user/v1/user.ext.proto

package v1

import (
	_ "github.com/cloudwego/hertz/cmd/hz/protobuf/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,required" form:"user_id,required" query:"user_id,required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_user_v1_user_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_v1_user_ext_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRes) Reset() {
	*x = GetUserInfoRes{}
	mi := &file_user_v1_user_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRes) ProtoMessage() {}

func (x *GetUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRes.ProtoReflect.Descriptor instead.
func (*GetUserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_v1_user_ext_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_user_v1_user_ext_proto protoreflect.FileDescriptor

const file_user_v1_user_ext_proto_rawDesc = "" +
	"\n" +
	"\x16user/v1/user.ext.proto\x12\auser.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/api/annotations.proto\x1a\fhz/api.proto\".\n" +
	"\x0eGetUserInfoReq\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x06userId\"$\n" +
	"\x0eGetUserInfoRes\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2h\n" +
	"\aUserExt\x12]\n" +
	"\vGetUserInfo\x12\x17.user.v1.GetUserInfoReq\x1a\x17.user.v1.GetUserInfoRes\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/user/getUserInfoBF\n" +
	"\x16dev.kratos.api.user.v1B\vUserProtoV1P\x01Z\x1dsolabar-server/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_ext_proto_rawDescOnce sync.Once
	file_user_v1_user_ext_proto_rawDescData []byte
)

func file_user_v1_user_ext_proto_rawDescGZIP() []byte {
	file_user_v1_user_ext_proto_rawDescOnce.Do(func() {
		file_user_v1_user_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_ext_proto_rawDesc), len(file_user_v1_user_ext_proto_rawDesc)))
	})
	return file_user_v1_user_ext_proto_rawDescData
}

var file_user_v1_user_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_user_ext_proto_goTypes = []any{
	(*GetUserInfoReq)(nil), // 0: user.v1.GetUserInfoReq
	(*GetUserInfoRes)(nil), // 1: user.v1.GetUserInfoRes
}
var file_user_v1_user_ext_proto_depIdxs = []int32{
	0, // 0: user.v1.UserExt.GetUserInfo:input_type -> user.v1.GetUserInfoReq
	1, // 1: user.v1.UserExt.GetUserInfo:output_type -> user.v1.GetUserInfoRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_ext_proto_init() }
func file_user_v1_user_ext_proto_init() {
	if File_user_v1_user_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_ext_proto_rawDesc), len(file_user_v1_user_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_ext_proto_goTypes,
		DependencyIndexes: file_user_v1_user_ext_proto_depIdxs,
		MessageInfos:      file_user_v1_user_ext_proto_msgTypes,
	}.Build()
	File_user_v1_user_ext_proto = out.File
	file_user_v1_user_ext_proto_goTypes = nil
	file_user_v1_user_ext_proto_depIdxs = nil
}
