// Code generated by protoc-gen-go-grpc-local. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: idgenerator/v1/id_generator.int.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

type idGeneratorIntClientLocal struct {
	impl IdGeneratorIntServer
}

func NewIdGeneratorIntClientLocal(impl IdGeneratorIntServer) IdGeneratorIntClient {
	return &idGeneratorIntClientLocal{impl}
}

func (c *idGeneratorIntClientLocal) GenerateId(ctx context.Context, in *GenerateIdRequest, opts ...grpc.CallOption) (*GenerateIdResponse, error) {
	return c.impl.GenerateId(ctx, in)
}
