// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8-devel
// 	protoc        v3.21.12
// source: idgenerator/v1/id_generator.int.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BizType int32

const (
	BizType_UNKNOWN      BizType = 0
	BizType_CHARACTER_ID BizType = 1
)

// Enum value maps for BizType.
var (
	BizType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CHARACTER_ID",
	}
	BizType_value = map[string]int32{
		"UNKNOWN":      0,
		"CHARACTER_ID": 1,
	}
)

func (x BizType) Enum() *BizType {
	p := new(BizType)
	*p = x
	return p
}

func (x BizType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizType) Descriptor() protoreflect.EnumDescriptor {
	return file_idgenerator_v1_id_generator_int_proto_enumTypes[0].Descriptor()
}

func (BizType) Type() protoreflect.EnumType {
	return &file_idgenerator_v1_id_generator_int_proto_enumTypes[0]
}

func (x BizType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizType.Descriptor instead.
func (BizType) EnumDescriptor() ([]byte, []int) {
	return file_idgenerator_v1_id_generator_int_proto_rawDescGZIP(), []int{0}
}

type GenerateIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizType       int32                  `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty" form:"biz_type" query:"biz_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdRequest) Reset() {
	*x = GenerateIdRequest{}
	mi := &file_idgenerator_v1_id_generator_int_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdRequest) ProtoMessage() {}

func (x *GenerateIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idgenerator_v1_id_generator_int_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdRequest.ProtoReflect.Descriptor instead.
func (*GenerateIdRequest) Descriptor() ([]byte, []int) {
	return file_idgenerator_v1_id_generator_int_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIdRequest) GetBizType() int32 {
	if x != nil {
		return x.BizType
	}
	return 0
}

type GenerateIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*GenerateIdResponse_IntId
	//	*GenerateIdResponse_StrId
	Id            isGenerateIdResponse_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdResponse) Reset() {
	*x = GenerateIdResponse{}
	mi := &file_idgenerator_v1_id_generator_int_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdResponse) ProtoMessage() {}

func (x *GenerateIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idgenerator_v1_id_generator_int_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdResponse.ProtoReflect.Descriptor instead.
func (*GenerateIdResponse) Descriptor() ([]byte, []int) {
	return file_idgenerator_v1_id_generator_int_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdResponse) GetId() isGenerateIdResponse_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GenerateIdResponse) GetIntId() int64 {
	if x != nil {
		if x, ok := x.Id.(*GenerateIdResponse_IntId); ok {
			return x.IntId
		}
	}
	return 0
}

func (x *GenerateIdResponse) GetStrId() string {
	if x != nil {
		if x, ok := x.Id.(*GenerateIdResponse_StrId); ok {
			return x.StrId
		}
	}
	return ""
}

type isGenerateIdResponse_Id interface {
	isGenerateIdResponse_Id()
}

type GenerateIdResponse_IntId struct {
	IntId int64 `protobuf:"varint,1,opt,name=int_id,json=intId,proto3,oneof"`
}

type GenerateIdResponse_StrId struct {
	StrId string `protobuf:"bytes,2,opt,name=str_id,json=strId,proto3,oneof"`
}

func (*GenerateIdResponse_IntId) isGenerateIdResponse_Id() {}

func (*GenerateIdResponse_StrId) isGenerateIdResponse_Id() {}

var File_idgenerator_v1_id_generator_int_proto protoreflect.FileDescriptor

const file_idgenerator_v1_id_generator_int_proto_rawDesc = "" +
	"\n" +
	"%idgenerator/v1/id_generator.int.proto\x12\x0eidgenerator.v1\".\n" +
	"\x11GenerateIdRequest\x12\x19\n" +
	"\bbiz_type\x18\x01 \x01(\x05R\abizType\"L\n" +
	"\x12GenerateIdResponse\x12\x17\n" +
	"\x06int_id\x18\x01 \x01(\x03H\x00R\x05intId\x12\x17\n" +
	"\x06str_id\x18\x02 \x01(\tH\x00R\x05strIdB\x04\n" +
	"\x02id*(\n" +
	"\aBizType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fCHARACTER_ID\x10\x012g\n" +
	"\x0eIdGeneratorInt\x12U\n" +
	"\n" +
	"GenerateId\x12!.idgenerator.v1.GenerateIdRequest\x1a\".idgenerator.v1.GenerateIdResponse\"\x00B[\n" +
	"\x1ddev.kratos.api.idgenerator.v1B\x12IdgeneratorProtoV1P\x01Z$solabar-server/api/idgenerator/v1;v1b\x06proto3"

var (
	file_idgenerator_v1_id_generator_int_proto_rawDescOnce sync.Once
	file_idgenerator_v1_id_generator_int_proto_rawDescData []byte
)

func file_idgenerator_v1_id_generator_int_proto_rawDescGZIP() []byte {
	file_idgenerator_v1_id_generator_int_proto_rawDescOnce.Do(func() {
		file_idgenerator_v1_id_generator_int_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idgenerator_v1_id_generator_int_proto_rawDesc), len(file_idgenerator_v1_id_generator_int_proto_rawDesc)))
	})
	return file_idgenerator_v1_id_generator_int_proto_rawDescData
}

var file_idgenerator_v1_id_generator_int_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idgenerator_v1_id_generator_int_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idgenerator_v1_id_generator_int_proto_goTypes = []any{
	(BizType)(0),               // 0: idgenerator.v1.BizType
	(*GenerateIdRequest)(nil),  // 1: idgenerator.v1.GenerateIdRequest
	(*GenerateIdResponse)(nil), // 2: idgenerator.v1.GenerateIdResponse
}
var file_idgenerator_v1_id_generator_int_proto_depIdxs = []int32{
	1, // 0: idgenerator.v1.IdGeneratorInt.GenerateId:input_type -> idgenerator.v1.GenerateIdRequest
	2, // 1: idgenerator.v1.IdGeneratorInt.GenerateId:output_type -> idgenerator.v1.GenerateIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idgenerator_v1_id_generator_int_proto_init() }
func file_idgenerator_v1_id_generator_int_proto_init() {
	if File_idgenerator_v1_id_generator_int_proto != nil {
		return
	}
	file_idgenerator_v1_id_generator_int_proto_msgTypes[1].OneofWrappers = []any{
		(*GenerateIdResponse_IntId)(nil),
		(*GenerateIdResponse_StrId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idgenerator_v1_id_generator_int_proto_rawDesc), len(file_idgenerator_v1_id_generator_int_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idgenerator_v1_id_generator_int_proto_goTypes,
		DependencyIndexes: file_idgenerator_v1_id_generator_int_proto_depIdxs,
		EnumInfos:         file_idgenerator_v1_id_generator_int_proto_enumTypes,
		MessageInfos:      file_idgenerator_v1_id_generator_int_proto_msgTypes,
	}.Build()
	File_idgenerator_v1_id_generator_int_proto = out.File
	file_idgenerator_v1_id_generator_int_proto_goTypes = nil
	file_idgenerator_v1_id_generator_int_proto_depIdxs = nil
}
