// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: idgenerator/v1/id_generator.int.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdGeneratorInt_GenerateId_FullMethodName = "/idgenerator.v1.IdGeneratorInt/GenerateId"
)

// IdGeneratorIntClient is the client API for IdGeneratorInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdGeneratorIntClient interface {
	GenerateId(ctx context.Context, in *GenerateIdRequest, opts ...grpc.CallOption) (*GenerateIdResponse, error)
}

type idGeneratorIntClient struct {
	cc grpc.ClientConnInterface
}

func NewIdGeneratorIntClient(cc grpc.ClientConnInterface) IdGeneratorIntClient {
	return &idGeneratorIntClient{cc}
}

func (c *idGeneratorIntClient) GenerateId(ctx context.Context, in *GenerateIdRequest, opts ...grpc.CallOption) (*GenerateIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIdResponse)
	err := c.cc.Invoke(ctx, IdGeneratorInt_GenerateId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGeneratorIntServer is the server API for IdGeneratorInt service.
// All implementations must embed UnimplementedIdGeneratorIntServer
// for forward compatibility.
type IdGeneratorIntServer interface {
	GenerateId(context.Context, *GenerateIdRequest) (*GenerateIdResponse, error)
	mustEmbedUnimplementedIdGeneratorIntServer()
}

// UnimplementedIdGeneratorIntServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdGeneratorIntServer struct{}

func (UnimplementedIdGeneratorIntServer) GenerateId(context.Context, *GenerateIdRequest) (*GenerateIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateId not implemented")
}
func (UnimplementedIdGeneratorIntServer) mustEmbedUnimplementedIdGeneratorIntServer() {}
func (UnimplementedIdGeneratorIntServer) testEmbeddedByValue()                        {}

// UnsafeIdGeneratorIntServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdGeneratorIntServer will
// result in compilation errors.
type UnsafeIdGeneratorIntServer interface {
	mustEmbedUnimplementedIdGeneratorIntServer()
}

func RegisterIdGeneratorIntServer(s grpc.ServiceRegistrar, srv IdGeneratorIntServer) {
	// If the following call pancis, it indicates UnimplementedIdGeneratorIntServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdGeneratorInt_ServiceDesc, srv)
}

func _IdGeneratorInt_GenerateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorIntServer).GenerateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGeneratorInt_GenerateId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorIntServer).GenerateId(ctx, req.(*GenerateIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdGeneratorInt_ServiceDesc is the grpc.ServiceDesc for IdGeneratorInt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdGeneratorInt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idgenerator.v1.IdGeneratorInt",
	HandlerType: (*IdGeneratorIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateId",
			Handler:    _IdGeneratorInt_GenerateId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idgenerator/v1/id_generator.int.proto",
}
