// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"log/slog"
	"solabar-server/internal/idgenerator/biz"
	"solabar-server/internal/idgenerator/service"
	biz2 "solabar-server/internal/user/biz"
	service2 "solabar-server/internal/user/service"
)

// Injectors from wire.go:

func wireApp(logger *slog.Logger) (*kratos.App, error) {
	idGeneratorUsecase := biz.NewIdGeneratorUsecase(logger)
	idGeneratorIntService := service.NewIdGeneratorIntService(idGeneratorUsecase)
	idGeneratorIntClient := newIdGeneratorIntClient(idGeneratorIntService)
	userUsecase := biz2.NewUserUsecase(logger, idGeneratorIntClient)
	userExtService := service2.NewUserExtService(userUsecase)
	server := newServer(userExtService)
	app := newApp(server)
	return app, nil
}
